name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # Runs only when changes are pushed to 'main' branch

permissions:
  contents: read  # Ensures workflow has permission to read repo contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Logout from Docker Hub  # Added for security
        run: docker logout